import yaml
import os
from exception import ConfigError

path = os.path.abspath(__file__)
dirname = os.path.dirname(os.path.dirname(path))
with open(os.path.join(dirname,'configtest.yaml'), 'r', encoding='utf-8') as f:
    data = yaml.load(stream=f, Loader=yaml.FullLoader)
    try:
        PLEX_URL = data['Server']['plex'].get('url')
        PLEX_TOKEN = data['Server']['plex'].get('token')
        EMBY_API = data['Server']['emby'].get('token')
        EMBY_URL = data['Server']['emby'].get('url')
        EMBY_USERNAME = data['Server']['emby'].get('username')
        EMBY_PW = data['Server']['emby'].get('password')
        ISPROXY = data['Proxy'].get('isproxy')
        PROXY = data['Proxy'].get('http')
        CONCURRENT_NUM = data['Env'].get('concurrent_num')
        LOG_PATH = data['Env'].get('log_path')
        LOG_LEVEL = data['Env'].get('log_level')
        LOG_EXPIRE = data['Env'].get('log_expire')
        TMDB_API = data['Env'].get('tmdb_api')
        PLEX_ROLE = data['Task']['plex']['roletask'].get('run')
        PLEX_ROLE_CRON = data['Task']['plex']['roletask'].get('crontab')
        PLEX_SORT = data['Task']['plex']['sorttask'].get('run')
        PLEX_SORT_CRON = data['Task']['plex']['sorttask'].get('crontab')
        PLEX_SACN = data['Task']['plex']['scantask'].get('run')
        PLEX_SACN_TASK = data['Task']['plex']['scantask'].get('library')
        EMBY_ROLE = data['Task']['emby']['roletask'].get('run')
        EMBY_ROLE_CRON = data['Task']['plex']['roletask'].get('crontab')
        EMBY_SORT = data['Task']['emby']['sorttask'].get('run')
        EMBY_SORT_CRON = data['Task']['emby']['sorttask'].get('crontab')
        EMBY_MERGE = data['Task']['emby']['mergetask'].get('run')
        EMBY_MERGE_CRON = data['Task']['emby']['mergetask'].get('crontab')
        EMBY_TITLE = data['Task']['emby']['titletask'].get('run')
        EMBY_TITLE_CRON = data['Task']['emby']['titletask'].get('crontab')
        EMBY_SACN = data['Task']['emby']['scantask'].get('run')
        EMBY_SACN_TASK = data['Task']['emby']['scantask'].get('library')
        SYNC_TASK = data['Task']['synctask'].get('run')
        FIRST_RUN = data['Task']['synctask'].get('isfirst')
    except:
        raise ConfigError('请检查config.yaml文件')